name: Delete Package Versions
on:
  registry_package:
    types: [published]

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: 'test-actions'
          min-versions-to-keep: 3
