name: Delete Package v1

on:
  push:
    branches:    
      - 'main'

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: 'my-package'
          min-versions-to-keep: 2
