name: Delete Package v2

on:
  push:
    branches:    
      - 'main'

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        run: |
          echo 'Starting retrieving versions of package'
          curl -H "Accept:application/vnd.github.v3+json" -H "Authorization:token ${{ secrets.MY_GITHUB_PAT }}" https://api.github.com/users/rodrigolfaria/packages/container/test-actions/versions -o /tmp/response.json
          numberOfVersion=`cat /tmp/response.json | grep -c id`
          echo `Number of versions: $numberOfVersion`

          if [ $numberOfVersion -gt 2 ]
            then
               idsToDelete=`cat /tmp/response.json | jq '.[2:]' | jq '.[] | .id'`

               for packageVersionId in $idsToDelete; do
                  echo `Calling URL to delete package with id: ${packageVersionId}`
                  urlToDelete=https://api.github.com/users/rodrigolfaria/packages/container/test-actions/versions/$packageVersionId
                  curl -X DELETE -H "Accept:application/vnd.github.v3+json" -H "Authorization:token ${{ secrets.MY_GITHUB_PAT }}" $urlToDelete
               done
          fi

          echo 'Finish execution'
        shell: bash
        #uses: actions/delete-package-versions@v3
        #1uses: smartsquaregmbh/delete-old-packages@v0.4.0
        #with:
          #package-name: "test-actions/my-package"
          #min-versions-to-keep: 2
          #token: ${{ secrets.MY_GITHUB_PAT }}
          #package-version-ids: 26992874
          #1keep: 2
          #1names: 'test-actions/my-package'
