name: Delete Package v2

on:
  push:
    branches:    
      - 'main'

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Package Versions
        run: |
          echo 'Retrieving versions of package'
          curl -H "Accept:application/vnd.github.v3+json" -H "Authorization:token ${MY_GITHUB_PAT}" https://api.github.com/users/rodrigolfaria/packages/container/test-actions/versions -o /tmp/response.json
          echo '1'
          numberOfVersion=`cat /tmp/response.json`
          #numberOfVersion=`cat /tmp/response.json | grep -c id`
          echo '2'
          #if [ $numberOfVersion -gt 2 ]
          #  then
          #     idsToDelete=`cat /tmp/response.json | jq '.[2:4]' | jq '.[] | .id'`
          #     echo $numberOfVersion
          #     for id in $idsToDelete; do
          #        urlToDelete=https://api.github.com/users/rodrigolfaria/packages/container/test-actions/versions/$id
          #        curl -X DELETE -H "Accept:application/vnd.github.v3+json" -H "Authorization:token ${MY_GITHUB_PAT}" $urlToDelete
          #     done
          #fi

          echo 'End'
        shell: bash
        #uses: actions/delete-package-versions@v3
        #1uses: smartsquaregmbh/delete-old-packages@v0.4.0
        #with:
          #package-name: "test-actions/my-package"
          #min-versions-to-keep: 2
          #token: ${{ secrets.MY_GITHUB_PAT }}
          #package-version-ids: 26992874
          #1keep: 2
          #1names: 'test-actions/my-package'
